version: '2'

services:

  volition:
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/code
    depends_on:
      - "db"

  db:
    image: postgres:9.4
    volumes:
      - volition_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  volition_db:
